# Generated by Django 5.2.5 on 2025-09-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_image_product_main_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
