# Generated by Django 5.2.5 on 2025-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_country_governorate_area_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterUniqueTogether(
            name='governorate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='governorate',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
