# Generated by Django 5.2.7 on 2025-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_heroslide_button_text_ar_heroslide_button_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='button_text_ar',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_text_en',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='short_description_ar',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text_ar',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text_en',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='short_description_ar',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='promogridcategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_ar',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_en',
        ),
        migrations.AlterField(
            model_name='promogridcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
